version: '2'

services:
  k6:
    image: 294395266716.dkr.ecr.us-east-1.amazonaws.com/loadtesting
    environment:
      - K6_OUT=influxdb=https://hilldale-fb76da79.influxcloud.net:8086/k6
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
