#!/bin/bash

echo "=> Setup Cluster Profile"
ecs-cli configure profile \
    --profile-name $ECS_PROFILE_NAME \
    --access-key $AWS_ACCESS_KEY \
    --secret-key $AWS_SECRET_KEY \
    && ecs-cli configure \
        --cluster $ECS_CLUSTER_NAME \
        --region $AWS_REGION \
        --default-launch-type EC2 \
        --config-name $ECS_PROFILE_NAME

# Create ECS cluster
echo "=> Creating ECS Cluster"
ecs-cli up \
    --keypair $INSTANCE_KEYPAIR \
    --capability-iam \
    --subnets $AWS_SUBNETS \
    --vpc $AWS_VPC \
    --size $ECS_CLUSTER_SIZE \
    --instance-type $ECS_INSTANCE_TYPE \
    --cluster-config $ECS_CLUSTER_CONFIG

echo "=> Take a nap and ECS will be ready when you wake up"
sleep 300

# Run ECS Task based on your configuration
echo "=> Running ECS Task"
ecs-cli compose \
    --file docker-compose.yml \
    --file aws-compose.yml \
    up \
    --create-log-groups \
    --cluster-config $ECS_CLUSTER_CONFIG
